# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: liamg/golang-opengl
    working_directory: /aminal
    steps:
      - checkout
      - run: go test -v ./...
  release:
    docker:
      - image: goreleaser/goreleaser
    steps:
      - checkout
      - run: goreleaser
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            tags: 
              only: /^.+/
            branches:
              ignore: /.*/